server:
  port: 8087

spring:
  application:
    name: mall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
