CREATE TABLE IF NOT EXISTS oms_order (
    id                  BIGINT        NOT NULL,
    order_sn            VARCHAR(64)   NULL,
    member_id           BIGINT        NULL,
    coupon_id           BIGINT        NULL,
    total_amount        DECIMAL(10,2) NULL DEFAULT 0,
    pay_amount          DECIMAL(10,2) NULL DEFAULT 0,
    freight_amount      DECIMAL(10,2) NULL DEFAULT 0,
    promotion_amount    DECIMAL(10,2) NULL DEFAULT 0,
    coupon_amount       DECIMAL(10,2) NULL DEFAULT 0,
    integration_amount  DECIMAL(10,2) NULL DEFAULT 0,
    discount_amount     DECIMAL(10,2) NULL DEFAULT 0,
    pay_type            INT           NULL,
    status              INT           NOT NULL DEFAULT 0,
    order_type          INT           NULL,
    receiver_name       VARCHAR(64)   NULL,
    receiver_phone      VARCHAR(20)   NULL,
    receiver_province   VARCHAR(64)   NULL,
    receiver_city       VARCHAR(64)   NULL,
    receiver_district   VARCHAR(64)   NULL,
    receiver_detail_address VARCHAR(255) NULL,
    receiver_post_code  VARCHAR(20)   NULL,
    pay_time            DATETIME      NULL,
    delivery_time       DATETIME      NULL,
    receive_time        DATETIME      NULL,
    cancel_time         DATETIME      NULL,
    remark              VARCHAR(500)  NULL,
    delete_status       INT           NOT NULL DEFAULT 0,
    source_type         INT           NULL,
    delivery_company    VARCHAR(64)   NULL,
    delivery_sn         VARCHAR(64)   NULL,
    auto_confirm_day    INT           NULL,
    integration         INT           NULL,
    growth              INT           NULL,
    bill_type           INT           NULL,
    bill_header         VARCHAR(255)  NULL,
    bill_content        VARCHAR(255)  NULL,
    bill_receiver_phone VARCHAR(20)   NULL,
    bill_receiver_email VARCHAR(64)   NULL,
    member_username     VARCHAR(64)   NULL,
    note                VARCHAR(500)  NULL,
    confirm_status      INT           NULL,
    use_integration     INT           NULL,
    comment_time        DATETIME      NULL,
    modify_time         DATETIME      NULL,
    create_time         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oms_order_item (
    id                  BIGINT        NOT NULL,
    order_id            BIGINT        NULL,
    order_sn            VARCHAR(64)   NULL,
    spu_id              BIGINT        NULL,
    sku_id              BIGINT        NULL,
    spu_name            VARCHAR(255)  NULL,
    sku_name            VARCHAR(255)  NULL,
    sku_img             VARCHAR(255)  NULL,
    sku_price           DECIMAL(10,2) NULL,
    sku_quantity        INT           NULL,
    sku_total_price     DECIMAL(10,2) NULL,
    promotion_amount    DECIMAL(10,2) NULL DEFAULT 0,
    coupon_amount       DECIMAL(10,2) NULL DEFAULT 0,
    create_time         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    spu_pic             VARCHAR(255)  NULL,
    spu_brand           VARCHAR(128)  NULL,
    category_id         BIGINT        NULL,
    sku_attrs_vals      VARCHAR(500)  NULL,
    integration_amount  DECIMAL(10,2) NULL DEFAULT 0,
    real_amount         DECIMAL(10,2) NULL DEFAULT 0,
    gift_integration    INT           NULL DEFAULT 0,
    gift_growth         INT           NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oms_order_operate_history (
    id                  BIGINT        NOT NULL,
    order_id            BIGINT        NULL,
    order_sn            VARCHAR(64)   NULL,
    operate_type        VARCHAR(64)   NULL,
    note                VARCHAR(500)  NULL,
    operate_by          BIGINT        NULL,
    operate_by_name     VARCHAR(64)   NULL,
    create_time         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oms_order_return_apply (
    id              BIGINT        NOT NULL,
    order_sn        VARCHAR(64)   NULL,
    order_id        BIGINT        NULL,
    sku_id          BIGINT        NULL,
    member_id       BIGINT        NULL,
    return_type     INT           NULL,
    reason          VARCHAR(255)  NULL,
    description     VARCHAR(500)  NULL,
    proof_imgs      VARCHAR(500)  NULL,
    return_amount   DECIMAL(10,2) NULL,
    status          INT           NOT NULL DEFAULT 0,
    handle_by       BIGINT        NULL,
    handle_note     VARCHAR(500)  NULL,
    handle_time     DATETIME      NULL,
    create_time     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    member_username VARCHAR(64)   NULL,
    return_name     VARCHAR(64)   NULL,
    return_phone    VARCHAR(20)   NULL,
    sku_img         VARCHAR(255)  NULL,
    sku_name        VARCHAR(255)  NULL,
    sku_brand       VARCHAR(128)  NULL,
    sku_attrs_vals  VARCHAR(500)  NULL,
    sku_count       INT           NULL,
    sku_price       DECIMAL(10,2) NULL,
    sku_real_price  DECIMAL(10,2) NULL,
    desc_pics       VARCHAR(500)  NULL,
    handle_man      VARCHAR(64)   NULL,
    receive_man     VARCHAR(64)   NULL,
    receive_phone   VARCHAR(20)   NULL,
    receive_note    VARCHAR(500)  NULL,
    company_address VARCHAR(255)  NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oms_refund_info (
    id              BIGINT        NOT NULL,
    order_return_id BIGINT        NULL,
    order_sn        VARCHAR(64)   NULL,
    refund_sn       VARCHAR(64)   NULL,
    refund_amount   DECIMAL(10,2) NULL,
    refund_status   INT           NOT NULL DEFAULT 0,
    refund_channel  VARCHAR(32)   NULL,
    refund_content  VARCHAR(500)  NULL,
    create_time     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    refund          DECIMAL(10,2) NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oms_payment_info (
    id              BIGINT        NOT NULL,
    order_sn        VARCHAR(64)   NULL,
    order_id        BIGINT        NULL,
    pay_sn          VARCHAR(64)   NULL,
    pay_type        INT           NULL,
    pay_amount      DECIMAL(10,2) NULL,
    total_amount    DECIMAL(10,2) NULL,
    subject         VARCHAR(255)  NULL,
    status          INT           NOT NULL DEFAULT 0,
    alipay_trade_no VARCHAR(64)   NULL,
    payment_status  VARCHAR(32)   NULL,
    callback_content VARCHAR(1024) NULL,
    callback_time   DATETIME      NULL,
    confirm_time    DATETIME      NULL,
    create_time     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
